<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>KiWin</AssemblyName>
    <RootNamespace>KiWin.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>KiWin.App.Program</StartupObject>
    <Version>1.0.0.0</Version>
    <Product>KiWin</Product>
    <Company>KiWin</Company>
    <Description>Simple utility to debloat Windows in 2 clicks.</Description>
    <ApplicationIcon>..\..\Assets\media\ICON.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody" Version="5.8.0-alpha0098" PrivateAssets="all" />
    <PackageReference Include="Fody" Version="6.8.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KiWin.Core\KiWin.Core.csproj" />
    <ProjectReference Include="..\KiWin.Utilities\KiWin.Utilities.csproj" />
    <ProjectReference Include="..\KiWin.Debloat\KiWin.Debloat.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\appbundle.zip" Condition="Exists('Resources\appbundle.zip')" LogicalName="appbundle.zip" />
  </ItemGroup>

</Project>
